### ISSUE TITLE
Package dependencies problem

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/portingdb#179]
I've found package datanommer-models which has a lot of dependencies in specfile [0] but in portingdb it has only two - for example, fedmsg is listed in specfile as build and runtime dependency but not in dependencies list in portingdb [1].

[0] http://pkgs.fedoraproject.org/cgit/rpms/python-datanommer-models.git/tree/python-datanommer-models.spec
[1] http://fedora.portingdb.xyz/pkg/python-datanommer-models/

**Comment by hroncok** [comment]
```
$ rpm -q --requires -p python-datanommer-models-0.6.5-5.fc25.noarch.rpm 
config(python-datanommer-models) = 0.6.5-5.fc25
fedmsg
python(abi) = 2.7
python-alembic
python-sqlalchemy >= 0.7
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by encukou** [comment]
The problem here is that `fedmsg` is practically a metapackage that doesn't itself depend on Python, so portingdb doesn't track it. What should happen here:
- If `python-datanommer-models` imports something from a fedmsg-related package that `fedmsg` brings in, it should depend on that package directly.
- If `fedmsg` contains a Python library, it should be named `python2-fedmsg` and depend on Python 2 in some way.
- If `fedmsg` and `python-datanommer-models` are really packaged correctly, record the exception in portingdb's `fedora-update.yaml`. It's a case that can't be handled automatically.

SQLAlchemy and Alembic are listed in portingdb.

**Comment by hroncok** [comment]
> SQLAlchemy and Alembic are listed in portingdb.

So is [fedmsg](http://fedora.portingdb.xyz/pkg/fedmsg/).

**Comment by frenzymadness** [comment]
Thank you for the explanation of possibilities. I've tried to investigate this issue more into deep and I've found some interesting information.

Fedmsg package was split to subpacgaes last year and IMHO datanommer packages should follow this and change dependencies to contains only necessary packages.

I think that this issue can be closed now because this is not problem in portingdb.

**Comment by encukou** [comment]
>> SQLAlchemy and Alembic are listed in portingdb.
>
> So is fedmsg.

I meant "listed as dependencies of `python-datanommer-models` in portingdb", but shortened too much. Sorry for the misunderstanding.
