### ISSUE TITLE
The list of misnamed packages is apparently incomplete

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#329]
See https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/Q225ZPP7R5OAI6MWDW7D5HUNMPIFV3EI/

On 10.8.2017 10:50, Juan Orti Alcaine wrote:
> 2017-08-10 4:52 GMT+02:00 Scott Talbert:
>> Where did your list of 'all python packages' come from?  I fear that there
>> are some missing because wxPython should be in there.
> 
> I also miss pytorctl in the list.

cc @keszybz @swt2c @jorti

**Comment by irushchyshyn** [comment]
`wxPython` and `pytorctl` are not identified as misnamed in portingdb, because they do not have a `python-` prefix in the built RPMs. 
Besides, having a `python{2,3}-` prefix is not mandatory e.g for applications. So we should either consider those cases manually or we could create some clever script, which would identify if it is a libraary or an application.

**Comment by swt2c** [comment]
That is a good point.  I'm not sure how you can easily tell a python library RPM from an application RPM.  Maybe if it installs anything to python2_sitelib or python2_sitearch?

**Comment by irushchyshyn** [comment]
Most applications would also have something in python2_sitelib, so I do not think we can use it as identificator :(

**Comment by encukou** [comment]
We do the best we can do automatically, so I'll close this.
