### ISSUE TITLE
Track Build Requires

### ISSUE THREAD

**Issue by irushchyshyn** [fedora-python/portingdb#382]
Track also packages that require Python or any Python package to build.

Create a new status (e.g "legacy leaf") that would display Released packages, whose python2 subpackages are not needed by anything.

 ~~Those are SRPMs which depend on one of [SEED_PACKAGES](https://github.com/fedora-python/portingdb/blob/master/dnf-plugins/py3query.py#L52). Add those packages to the database, and display SRPM python requirements on the package page above RPMs.~~

This is an initial overview of the requirement. @encukou let me know if you have other ideas regarding how they should be viewed.

**Comment by encukou** [comment]
We should rather track all packages that BuildRequire *any* python package (or at least, any py2 package). It could be done the same way as [non-Python pkgs for misnamed stuff](http://fedora.portingdb.xyz/namingpolicy/#require-misnamed-non-python), i.e. just use simple names rather than a full-fledged entry.

The final outcome in portingdb should be to show "legacy leaf" packages, i.e. `released` ones whose py2 subpackages aren't needed for anything else in Fedora. (And that should be tracked as a new status.)

**Comment by irushchyshyn** [comment]
I see now, thanks for clarifying it for me. I will start with data collection for that.

**Comment by encukou** [comment]
I believe BuildRequires are tracked well now. @irushchyshyn, if you had any more improvements in mind, could you re-open this?

**Comment by irushchyshyn** [comment]
Sure. The only thing we could add is displaying non-Python `Dependent packages` on the package page, but this is not of high priority. They are taken into account when identifying Python 2 leaves, but just are not displayed.
