### ISSUE TITLE
Track and bother non-python packages that have python2 deps

### ISSUE THREAD

**Issue by hroncok** [fedora-python/portingdb#583]
I'm opening this here, because I want to coordinate somewhere. Portingdb doesn't necessarily need any changes.

We have some packages that depend on Python 2 packages. We should determine a way how to bother them, or else their maintainers (and users) will be surprised.

Imagine *yakshaver* uses (runs on) Python 2 and we track it.
@frenzymadness open a bugzilla and the *yakshaver* maintainers say "yeah, we don't care, let's retire it in November".

However, *yakdashboard* uses *yakshaver*. *yakdashboard* is written in JavaScript, so the maintainers don't have a clue about any of this. In November *yakshaver* disappears and the *yakdashboard* maintainers are surprised by this. All the yak farmers are sad...

How to deal with this kind of things?

**Comment by frenzymadness** [comment]
Let's talk about non-leaf packages only. There are too many corner cases but I think that most commons are:
* A maintainer doesn't care (no matter whether they say it or ignore us completely) and a package is orphaned as soon as possible so maintainers of dependent packages should get a notification about it
* A maintainer has a plan to port a package to Python 3:
  * it happens before mid of November ✅
  * it does not happen before mid of November and a maintainer requests an exception
  * it does not happen before mid of November and a maintainer gives up their effort

I think that what we can do for the last two cases is that we can prepare a special comment for bugzillas with a plan (maybe those marked as triaged) and add maintainers of dependent packages to Cc to make them aware that something might happen to their dependencies.
As I'm thinking about it a separated email might be better first step than adding them to bugzillas because then they'd receive all subsequent notifications which might be too much.

What do you think about it? Do you have another possible scenario in mind missing here?

**Comment by hroncok** [comment]
For example I've said in three bugs: "Yes, I plan to retire the package in November." is that a reply you got form others, or it is my special case?

**Comment by frenzymadness** [comment]
Very special case not treated as special because you know what you are doing. Otherwise, I'd prefer to orphan/retire a package now rather than later.

**Comment by hroncok** [comment]
Composing a "this is what we plan to remove in November, and those are all the packages affected, you are bcced if you are the maintainer" e-mail sounds good.

**Comment by frenzymadness** [comment]
Let's wait until October. By then we should have a clearer image of what we'll do and also all of the unresponsive maintainer's packages will be orphaned so we can add them to the mail as a separated list.

What do you think?

**Comment by hroncok** [comment]
ack

**Comment by hroncok** [comment]
The e-mails are being sent.
